version: '3'

services:
  scipy:
    build: .
    ports:
      - '8888:8888'
    volumes:
      - './work:/home/jovyan/work'

    command: start-notebook.sh
  # stanford_nlp:
  #   image: nlpbox/corenlp
  #   ports:
  #     - '9000:9000'